version: '3'

services:
  login:
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile
    entrypoint:
      - ./target/debug/login
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: