version: '3'

services:
  comment:
    image: rust-supermarket
    restart: always
    network_mode: host
    entrypoint:
      - ./target/debug/comment
    ports:
      - 8083:8083
    depends_on:
      - user-data
  sale:
    image: rust-supermarket
    restart: always
    network_mode: host
    entrypoint:
      - ./target/debug/sale
    ports:
      - 8081:8081
    depends_on:
      - user-data
  user-data:
    image: rust-supermarket
    restart: always
    network_mode: host
    entrypoint:
      - ./target/debug/user_data
    ports:
      - 8082:8082
      - 8090:8090
    depends_on:
      - login
  login:
    image: rust-supermarket
    network_mode: host
    restart: always
    entrypoint:
      - ./target/debug/login
    ports:
      - 8080:8080
      - 8089:8089
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
    network_mode: host
    ports:
      - 6379:6379
  db:
    image: mysql:latest
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: